services:
  
  # API GATEWAY SERVICE | REVERSE PROXY
  api_gwt:
    build: api_gwt

# LOAD BALANCER
  web:
    build: network_layer
    ports:
      - 8080:8080

    # google.com

# CORE REPORT MODULE
  m_reports:
    build: 
      context: ./modules/reports

# CORE AND FUNCTIONS
  core:
    build: 
      context: ./modules/core
